### ISSUE TITLE
Stack for unknown member

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/Kira#6]
[ForkJoinPool.commonPool-worker-2] ERROR RestAction - RestAction queue returned failure: [ErrorResponseException] 10007: Unknown Member
net.dv8tion.jda.api.exceptions.ContextException
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:52)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:62)
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:168)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:303)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:272)
        at com.github.maxopoly.kira.user.DiscordRoleManager.lambda$syncFully$7(DiscordRoleManager.java:105)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.github.maxopoly.kira.user.DiscordRoleManager.syncFully(DiscordRoleManager.java:102)
        at com.github.maxopoly.kira.user.DiscordRoleManager.lambda$new$0(DiscordRoleManager.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Maxopoly** [comment]
Should be fixed by https://github.com/CivClassic/Kira/commit/3c0c9727b27b4b9c8d1d1afcbf779734707d2b5b

**Comment by Maxopoly** [comment]
Not fixed, reopening

**Comment by Maxopoly** [comment]
Updated exact stack
```
net.dv8tion.jda.api.exceptions.ContextException
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:189)
        at net.dv8tion.jda.internal.requests.DeferredRestAction.queue(DeferredRestAction.java:113)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:411)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:377)
        at com.github.maxopoly.kira.user.DiscordRoleManager.lambda$syncFully$7(DiscordRoleManager.java:107)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.github.maxopoly.kira.user.DiscordRoleManager.syncFully(DiscordRoleManager.java:103)
        at com.github.maxopoly.kira.user.DiscordRoleManager.lambda$new$0(DiscordRoleManager.java:37)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Maxopoly** [comment]
Seemingly fixed by https://github.com/CivClassic/Kira/commit/fce7665e1b017ea2222a7384cc655294621ae058
